AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'exercise/**/*'

Metrics/MethodLength:
  Max: 17
Metrics/ParameterLists:
  Max: 6
Metrics/BlockLength:
  Max: 30

Naming/MethodParameterName:
  AllowedNames:
    - 'x'
    - 'y'
